### ISSUE TITLE
PoolManager initializes HTablePool too expensively.

### ISSUE THREAD

**Issue by juneng603** [mushkevych/surus#1]
basically. HTablePool initializes it's pool size as a Integer.MAX_VALUE if it has no arguments. 
If clients uses our library too heavily, it could cause lack of resources in a HBase.

HBase 0.92.1

``` java
  /**
   * Default Constructor. Default HBaseConfiguration and no limit on pool size.
   */
  public HTablePool() {
    this(HBaseConfiguration.create(), Integer.MAX_VALUE);
  }
```

**Comment by mushkevych** [comment]
This initialization was a work-around for older version of the HBase.
Particularly, HTablePool was throwing exception on issuing additional instance on top of pre-defined number.

I guess its safe to change it now with release of CDH4.
