### ISSUE TITLE
can you provide one example py?

### ISSUE THREAD

**Issue by rfyiamcool** [mushkevych/surus#4]
can you provide one example py?

**Comment by mushkevych** [comment]
you can look at the model definition examples in the test folder:
https://github.com/mushkevych/surus/tree/master/test/com/reinvent/surus

please also note that modern data serialization technologies (such as protobuf from Google [1]) offer much more features and have SDK available in other languages (Python, C++, etc)

[1] https://developers.google.com/protocol-buffers/?hl=en
